version: '2'
services:
  # Mysql Database
  dbmysql:
    image: mysql/mysql-server:5.5.47
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

  # Postgresql Database
  dbpost:
    image: postgres:9.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root

  # Redis server
  redis:
    image: tenstartups/redis
    command: redis-server --appendonly yes --protected-mode no
    ports:
      - 6379:6379

  # NGINX Server for varsitytutors.dev
  nginx:
    build: nginx_build
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - "dockerhost:172.31.31.1" # Ensure you run `sudo ifconfig lo0 alias 172.31.31.1` to create the loop back alias

  # Mailcatcher for emails
  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

  poxa:
    image: edgurgel/poxa-automated
    volumes:
      - ./config/poxa.conf:/app/poxa/running-config/poxa.conf
    environment:
      PORT: 8080
      POXA_APP_KEY: 4bc2798ae34bb1563a3a
      POXA_SECRET: 234fb2f3ae7666dc39bd
      POXA_APP_ID: 55447
    ports:
      - 8080:8080
